-- insert into students(cgpa ,enrollment_date ,first_name,last_name,middle_name,student_number,is_international)
-- values (3.3,'2020-02-20','elyana','samuel','ghide','123467','yes');
--
-- insert into students(cgpa ,enrollment_date ,first_name,last_name,middle_name,student_number,is_international)
-- values (3.4,'2020-02-08','samuel','jhone','jack','123458','no');
--
-- insert into students(cgpa ,enrollment_date ,first_name,last_name,middle_name,student_number,is_international)
-- values (3.9,'2020-03-21','hana','yonas','abel','123461','no');
--
